#MTR Traffic Addon config
#Tue Aug 11 18:25:44 CST 2026
trafficVehicleMaterializationMarginChunks=2
trafficVehicleSimulationDistanceBlocks=32
trafficVehicleUnrenderedLifetimeSeconds=30
trafficVehicleVisibilityDistanceBlocks=16
﻿\#MTR=Traffic Addon config
